Re build elastalert image
skuid/dockerfiles pull request #4
Opened 2017-06-13 20:42 UTC by tpayne1

2017-06-13 20:44 UTC, micahhausler requested changes

2017-06-13 20:44 UTC, micahhausler commented on elastalert/Dockerfile
> +LABEL "Python_version"= "2.7.13"
You should probably delete those trailing equal signs

2017-06-13 20:46 UTC, micahhausler commented on elastalert/Dockerfile
> +LABEL "Python_version"= "2.7.13"
Ok, actually keep the equal sign, remove the space https://docs.docker.com/engine/reference/builder/#label

2017-06-13 20:57 UTC, micahhausler approved these changes

2017-06-13 20:57 UTC, merged

2017-06-14 01:29 UTC, ethanfrogers commented on elastalert/Dockerfile
> +LABEL "Python_version"= "2.7.13"
could we standardize on either all lowercase or all uppercase labels?